
import { Report, User } from './types';

export const mockUsers: User[] = [
  { id: '1', email: 'citizen@example.com', fullName: 'Juan Dela Cruz', phone: '09123456789', userType: 'citizen', accountVerificationStatus: 'unverified' },
  { id: '2', email: 'admin@respond.ph', fullName: 'PDRRMO Supervisor', phone: '09987654321', userType: 'pdrrmo_admin', accountVerificationStatus: 'verified' },
  { id: '3', email: 'bfp@respond.ph', fullName: 'Fire Officer 1', phone: '09111111111', userType: 'agency_admin', agency: 'BFP', accountVerificationStatus: 'verified' },
  { id: '4', email: 'pnp@respond.ph', fullName: 'Police Captain', phone: '09222222222', userType: 'agency_admin', agency: 'PNP', accountVerificationStatus: 'verified' },
  { id: '5', email: 'pcg@respond.ph', fullName: 'Coast Guard Petty Officer', phone: '09333333333', userType: 'agency_admin', agency: 'PCG', accountVerificationStatus: 'verified' },
];

export const initialReports: Report[] = [
  {
    id: 'REP-001',
    userId: '1',
    userName: 'Juan Dela Cruz',
    userPhone: '09123456789',
    userIsVerified: false,
    incidentType: 'fire',
    description: 'Structure fire reported at the local market area. Smoke is thick and dark.',
    latitude: 5.0713,
    longitude: 119.7821,
    addressLandmark: 'Bongao Public Market',
    verificationStatus: 'verified',
    priorityLevel: 'critical',
    currentStatus: 'assigned',
    assignedAgency: 'BFP',
    imageUrl: 'https://images.unsplash.com/photo-1544033527-b192daee1f5b?auto=format&fit=crop&q=80&w=400',
    createdAt: new Date(Date.now() - 3600000).toISOString(),
    updatedAt: new Date().toISOString()
  },
  {
    id: 'REP-002',
    userId: '1',
    userName: 'Juan Dela Cruz',
    userPhone: '09123456789',
    userIsVerified: false,
    incidentType: 'medical',
    description: 'Road accident involving a motorcycle. Driver needs assistance.',
    latitude: 5.0689,
    longitude: 119.7754,
    addressLandmark: 'Near Provincial Hospital',
    verificationStatus: 'pending',
    priorityLevel: 'none',
    currentStatus: 'submitted',
    assignedAgency: 'NONE',
    imageUrl: 'https://images.unsplash.com/photo-1581075500598-f46a661bbd2a?auto=format&fit=crop&q=80&w=400',
    createdAt: new Date(Date.now() - 1800000).toISOString(),
    updatedAt: new Date().toISOString()
  },
  {
    id: 'REP-003',
    userId: '1',
    userName: 'Juan Dela Cruz',
    userPhone: '09123456789',
    userIsVerified: false,
    incidentType: 'other',
    description: 'M/L San Jose motorlaunch failed engine. Drifting 3 miles offshore with 12 passengers. Dead in the water.',
    latitude: 5.0212, // Adjusted further south-west into the Celebes Sea
    longitude: 119.7110, // Adjusted further west to be clearly in the water
    addressLandmark: '3NM SW of Bongao Peak (Sea)',
    verificationStatus: 'verified',
    priorityLevel: 'high',
    currentStatus: 'assigned',
    assignedAgency: 'PCG',
    imageUrl: 'https://images.unsplash.com/photo-1544551763-46a013bb70d5?auto=format&fit=crop&q=80&w=400',
    createdAt: new Date(Date.now() - 900000).toISOString(),
    updatedAt: new Date().toISOString()
  },
  {
    id: 'REP-004',
    userId: '1',
    userName: 'Juan Dela Cruz',
    userPhone: '09123456789',
    userIsVerified: false,
    incidentType: 'crime',
    description: 'Disturbance at a local convenience store. Possible shoplifting turned aggressive.',
    latitude: 5.0672,
    longitude: 119.7712,
    addressLandmark: 'D\'Market Square',
    verificationStatus: 'pending',
    priorityLevel: 'medium',
    currentStatus: 'submitted',
    assignedAgency: 'NONE',
    imageUrl: 'https://images.unsplash.com/photo-1517486808906-6ca8b3f04846?auto=format&fit=crop&q=80&w=400',
    createdAt: new Date(Date.now() - 450000).toISOString(),
    updatedAt: new Date().toISOString()
  },
  {
    id: 'REP-005',
    userId: '1',
    userName: 'Juan Dela Cruz',
    userPhone: '09123456789',
    userIsVerified: true,
    incidentType: 'flood',
    description: 'Severe gutter-level flooding due to heavy rains. Drainage blocked in the main intersection.',
    latitude: 5.0701,
    longitude: 119.7785,
    addressLandmark: 'Capitol Site Road',
    verificationStatus: 'verified',
    priorityLevel: 'low',
    currentStatus: 'on_scene',
    assignedAgency: 'BFP',
    imageUrl: 'https://images.unsplash.com/photo-1547683905-f686c993aae5?auto=format&fit=crop&q=80&w=400',
    createdAt: new Date(Date.now() - 7200000).toISOString(),
    updatedAt: new Date().toISOString()
  },
  {
    id: 'REP-006',
    userId: '1',
    userName: 'Juan Dela Cruz',
    userPhone: '09123456789',
    userIsVerified: true,
    incidentType: 'medical',
    description: 'Passenger collapsed at the pier. Needs immediate medical attention.',
    latitude: 5.0645,
    longitude: 119.7735,
    addressLandmark: 'Bongao Port Terminal',
    verificationStatus: 'verified',
    priorityLevel: 'high',
    currentStatus: 'submitted',
    assignedAgency: 'NONE',
    imageUrl: 'https://images.unsplash.com/photo-1516574187841-cb9cc2ca948b?auto=format&fit=crop&q=80&w=400',
    createdAt: new Date(Date.now() - 300000).toISOString(),
    updatedAt: new Date().toISOString()
  },
  {
    id: 'REP-007',
    userId: '1',
    userName: 'Juan Dela Cruz',
    userPhone: '09123456789',
    userIsVerified: false,
    incidentType: 'accident',
    description: 'Minor collision between a tricycle and a jeepney. No serious injuries but blocking traffic.',
    latitude: 5.0850,
    longitude: 119.7550,
    addressLandmark: 'Airport Road Intersection',
    verificationStatus: 'pending',
    priorityLevel: 'low',
    currentStatus: 'submitted',
    assignedAgency: 'NONE',
    imageUrl: 'https://images.unsplash.com/photo-1590103306893-6c8f69165351?auto=format&fit=crop&q=80&w=400',
    createdAt: new Date(Date.now() - 120000).toISOString(),
    updatedAt: new Date().toISOString()
  }
];
